
screenerCfgs:
   - id : HoldingScreener
     priority : 100
     
   - id : ManualInclusionScreener
     priority : 99
     attributes :
        nseSymbols : NIFTYBEES, SETFGOLD
        
   - id : IndexScreener
     priority : 98
     attributes :
        includedIndexes : Nifty 200
        
   - id : IndicatorScreener
     priority : 90
     attributes :
        includedMCInsights : MID RANGE, MID-RANGE, STRONG
        minMcEssentialScore : 40
        minMarketCap : 20000
        betaRange : 0.3:1.7
        minCagrEbit : 5
        minPiotroskiScore : 4
        maxPe : 100

attributeEvaluatorCfgs:
   - id : GoodnessEvaluator
     attributes :
        betaWt : 5
        piotroskiScoreWt : 10
        mktCapWt : 10
        mcEssentialScoreWt : 20
        peWt : 25
        cagrWt : 30
   - id : TrendEvaluator
