- date : 26-Jan-2023
  day : Thursday
  name : Republic Day        

- date : 08-Mar-2023
  day : Wednesday
  name : Holi      

- date : 30-Mar-2023
  day : Thursday
  name : Ram Navami    

- date : 04-Apr-2023
  day : Tuesday
  name : Mahavir Jayanti   

- date : 07-Apr-2023
  day : Friday
  name : Good Friday   

- date : 14-Apr-2023
  day : Friday
  name : Dr.Baba Saheb Ambedkar Jayanti    

- date : 21-Apr-2023
  day : Friday
  name : Id-ul-fitr (Ramzan Id)    

- date : 01-May-2023
  day : Monday
  name : Maharashtra Day     

- date : 28-Jun-2023
  day : Wednesday
  name : Id-ul-adha (Bakri Id)      

- date : 15-Aug-2023
  day : Tuesday
  name : Independence Day     

- date : 19-Sep-2023
  day : Tuesday
  name : Ganesh Chaturthi      

- date : 02-Oct-2023
  day : Monday
  name : Mahatma Gandhi Jayanti      

- date : 24-Oct-2023
  day : Tuesday
  name : Dasara      

- date : 14-Nov-2023
  day : Tuesday
  name : Diwali Balipratipada       

- date : 27-Nov-2023
  day : Monday
  name : Gurunanak Jayanti      

- date : 25-Dec-2023
  day : Monday
  name : Christmas     