envVars:
   basePackageName : com.sandy.capitalyst.server.job

jobConfigs:
   - identity : NSEBhavcopyRefreshJob
     active : false
     className : ${basePackageName}.equity.eodrefresh.NSEBhavcopyImportJob
     description : Refreshes latest price for equity
     cronSchedule : 0/30 * * * * ?
     jobData :
        key1 : value1
        key2 : value2
        
   - identity : MFNavRefreshJob
     active : true
     className : ${basePackageName}.mf.eodrefresh.MFEODNAVRefreshJob
     description : Refreshes latest NAV for MF
     cronSchedule : 0 */10 * * * ?
