#!/bin/bash

cd `dirname $0`
SCRIPTDIR=`pwd`
cd -

CP="$SCRIPTDIR/config:$SCRIPTDIR/lib/*"

java -Djava.awt.headless=false \
     -Dcom.sun.management.jmxremote \
     -Dcom.sun.management.jmxremote.port=9010 \
     -Dcom.sun.management.jmxremote.local.only=false \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Dcom.sun.management.jmxremote.ssl=false \
     -Djava.rmi.server.hostname=192.168.0.116 \
     --add-opens=java.base/java.lang=ALL-UNNAMED \
     --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
     --illegal-access=warn \
     -classpath $CP \
     com.sandy.capitalyst.server.CapitalystServer 

