#!/bin/bash

COOKIE_JAR_FILE="$HOME/projects/workspace/capitalyst/cookies/nse-itd-cookie-jar.txt"
COOKIE_PROPERTIES="$HOME/projects/workspace/capitalyst/cookies/nse-itd-cookie.properties"

curl -c $COOKIE_JAR_FILE \
     --silent \
     --output /dev/null \
     'https://www.nseindia.com/market-data/live-equity-market' \
     -H 'authority: www.nseindia.com' \
     -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
     -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7' \
     -H 'cache-control: max-age=0' \
     -H 'sec-ch-ua: "Chromium";v="106", "Not;A=Brand";v="99"' \
     -H 'sec-ch-ua-mobile: ?0' \
     -H 'sec-ch-ua-platform: "macOS"' \
     -H 'sec-fetch-dest: document' \
     -H 'sec-fetch-mode: navigate' \
     -H 'sec-fetch-site: none' \
     -H 'sec-fetch-user: ?1' \
     -H 'upgrade-insecure-requests: 1' \
     -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
     --compressed

cat $COOKIE_JAR_FILE | \
    grep '#HttpOnly' | \
    awk '{print $6 "=" $7}' > $COOKIE_PROPERTIES